language: php

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer install

cache:
  directories:
  - $HOME/.composer/cache
